name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node-version: "20"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Install modules
        run: yarn install --immutable
      - name: Run ESLint & Prettier
        run: yarn run lint

  testBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Install modules
        run: yarn install --immutable
      - name: Build
        run: yarn run build
